name: Publish Docker image

on:
  schedule:
    - cron: '15 1 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths: 
      - 'docker/scratch-annotation.Dockerfile'
      - '.github/workflows/docker-basic-publish.yml'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: oandrefonseca/scratch-annotation
          flavor: |
            latest=false
            suffix=-${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/scratch-annotation.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
